# Generated by Django 6.0.5 on 2026-06-12 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_morador', models.CharField(max_length=100)),
                ('numero_pedido', models.CharField(max_length=50)),
                ('andar_destino', models.IntegerField(choices=[(0, 'Térreo - Recepção'), (1, '1º Andar - Apartamento 101'), (2, '2º Andar - Apartamento 201'), (3, '3º Andar - Apartamento 301')])),
                ('status', models.CharField(choices=[('aguardando', 'Aguardando envio'), ('subindo', 'Subindo para o andar'), ('aguardando_retirada', 'Aguardando retirada'), ('retornando', 'Retornando ao térreo'), ('finalizado', 'Finalizado')], default='aguardando', max_length=30)),
                ('executado', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
